AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  llrt-sam

  Sample SAM Template for llrt-sam

Globals:
  Function:
    Timeout: 3

Resources:
  LlrtLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ../../llrt-lambda-arm64.zip
      CompatibleRuntimes:
        - provided.al2023
      CompatibleArchitectures:
        - arm64
  LlrtPutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: llrt-put-item/
      Handler: app.lambdaHandler
      Runtime: provided.al2023
      Timeout: 30
      MemorySize: 1024
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Architectures:
        - arm64
      Layers:
        - !Ref LlrtLayer
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        External:
          - "@aws-sdk"
          - "@smithy"
          - uuid
        Minify: false
        Target: "es2020"
        Sourcemap: false
        Format: esm
        OutExtension:
          - .js=.mjs
        EntryPoints:
          - app.ts



  NodeJsPutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodejs-put-item/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 30
      MemorySize: 1024
      Architectures:
      - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts

  DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "llrt-sam-table"
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

Outputs:
  LlrtPutItemFunction:
    Description: "Llrt Put Item Lambda Function ARN"
    Value: !GetAtt LlrtPutItemFunction.Arn
  NodeJsPutItemFunction:
    Description: "NodeJs Put Item Lambda Function ARN"
    Value: !GetAtt NodeJsPutItemFunction.Arn

